"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
export type ApplicationPlanStatus = "considering" | "preparing" | "ready" | "applied" | "closed" | "cancelled";
export type ApplicationPlan = { id: string; recruitmentId: string; specialtyName: string; branch: string; recruitmentCategory: string; applicationStartAt?: string; applicationEndAt?: string; enlistmentMonth?: string; status: ApplicationPlanStatus; addedAt: string; checklist: Record<string, boolean> };
type AddInput = Omit<ApplicationPlan, "id" | "addedAt" | "status" | "checklist">;
type PlannerContext = { plans: ApplicationPlan[]; addPlan: (input: AddInput) => void; removePlan: (id: string) => void; updateStatus: (id: string, status: ApplicationPlanStatus) => void; toggleChecklist: (id: string, key: string) => void };
const Context = createContext<PlannerContext | null>(null); const storageKey = "teukgeup-honeybee-application-plans-v1";
export function ApplicationPlannerProvider({ children }: { children: React.ReactNode }) { const [plans, setPlans] = useState<ApplicationPlan[]>(() => { if (typeof window === "undefined") return []; try { const value = JSON.parse(localStorage.getItem(storageKey) || "[]"); return Array.isArray(value) ? value.filter((item) => item && typeof item.id === "string" && typeof item.recruitmentId === "string") : []; } catch { localStorage.removeItem(storageKey); return []; } }); useEffect(() => { localStorage.setItem(storageKey, JSON.stringify(plans)); }, [plans]); const value = useMemo<PlannerContext>(() => ({ plans, addPlan: (input) => setPlans((current) => current.some((plan) => plan.recruitmentId === input.recruitmentId) ? current : [...current, { ...input, id: crypto.randomUUID(), status: "considering", addedAt: new Date().toISOString(), checklist: {} }]), removePlan: (id) => setPlans((current) => current.filter((plan) => plan.id !== id)), updateStatus: (id, status) => setPlans((current) => current.map((plan) => plan.id === id ? { ...plan, status } : plan)), toggleChecklist: (id, key) => setPlans((current) => current.map((plan) => plan.id === id ? { ...plan, checklist: { ...plan.checklist, [key]: !plan.checklist[key] } } : plan)) }), [plans]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useApplicationPlanner() { const context = useContext(Context); if (!context) throw new Error("ApplicationPlannerProvider is required"); return context; }
