import { notFound } from "next/navigation";
import { freshnessLabel, getDataFreshness } from "@/lib/data-freshness";
import { officialSpecialties, officialSpecialtyCounts } from "@/lib/official-specialties";

export default function DataOperationsPage() {
  if (process.env.NODE_ENV === "production") notFound();
  const lastSyncAt = officialSpecialties[0]?.source.retrievedAt;
  const freshness = getDataFreshness(lastSyncAt);
  return <main className="min-h-screen bg-stone-50 px-5 py-8 text-stone-950"><div className="mx-auto max-w-5xl"><p className="text-sm font-semibold text-emerald-700">개발 전용 · Data Operations</p><h1 className="mt-2 text-3xl font-bold">특기 데이터 운영 현황</h1><p className="mt-3 text-stone-600">이 화면은 개발 환경에서만 보이며, 운영 제어 기능은 제공하지 않습니다.</p><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-stone-500">번들 특기</p><p className="mt-2 text-2xl font-bold">{officialSpecialties.length}</p></article><article className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-stone-500">공식 동기화</p><p className="mt-2 text-lg font-bold">{lastSyncAt ? new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium" }).format(new Date(lastSyncAt)) : "기록 없음"}</p></article><article className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-stone-500">신선도</p><p className="mt-2 text-lg font-bold">{freshnessLabel[freshness]}</p></article><article className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-stone-500">데이터 검증</p><p className="mt-2 text-lg font-bold">npm run validate:data</p></article></section><section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">군종별 커버리지</h2><dl className="mt-5 grid gap-3 sm:grid-cols-4">{Object.entries(officialSpecialtyCounts).map(([branch, count]) => <div className="rounded-xl bg-stone-50 p-4" key={branch}><dt className="text-sm text-stone-500">{branch}</dt><dd className="mt-1 text-xl font-bold">{count}개</dd></div>)}</dl></section><section className="mt-8 rounded-3xl border border-amber-200 bg-amber-50 p-6 text-sm leading-6 text-amber-950"><h2 className="font-bold">검토 대기 항목</h2><p className="mt-2">다음 동기화가 성공하면 코드 매핑이 없는 공식 특기는 <code>data/review/unmatched-specialties.json</code>에 기록됩니다. 파일은 추천 데이터에 자동 반영되지 않습니다.</p></section></div></main>;
}
